"""Convert TCP descriptors to Anthropic API tool schema format.

Schema parity invariant: both arms of a paired benchmark use schemas
generated by the same function.  The filtered arm selects a subset of
the pre-generated list -- no re-generation, no reformatting.
"""

from __future__ import annotations

from typing import Sequence

from tcp.core.descriptors import (
    CapabilityDescriptor,
    CapabilityFlags,
    ParameterType,
)
from tcp.harness.corpus import CorpusEntry
from tcp.harness.models import ToolRecord


_PARAM_TYPE_MAP = {
    ParameterType.STRING: "string",
    ParameterType.INTEGER: "integer",
    ParameterType.FLOAT: "number",
    ParameterType.BOOLEAN: "boolean",
    ParameterType.ENUM: "string",
    ParameterType.ARRAY: "array",
    ParameterType.OBJECT: "object",
    ParameterType.FILE: "string",
    ParameterType.BINARY: "string",
}


def _infer_input_schema(descriptor: CapabilityDescriptor) -> dict:
    """Build JSON Schema input_schema from descriptor commands."""
    commands = descriptor.commands
    if isinstance(commands, dict):
        commands = list(commands.values())
    if not commands:
        return {"type": "object", "properties": {}}

    cmd = commands[0]
    if cmd.parameters:
        properties: dict = {}
        required: list[str] = []
        for p in cmd.parameters:
            prop: dict = {"type": _PARAM_TYPE_MAP.get(p.type, "string")}
            if p.description:
                prop["description"] = p.description
            if p.enum_values:
                prop["enum"] = p.enum_values
            properties[p.name] = prop
            if p.required:
                required.append(p.name)
        schema: dict = {"type": "object", "properties": properties}
        if required:
            schema["required"] = required
        return schema

    # No explicit parameters -- provide a minimal input property
    return {
        "type": "object",
        "properties": {
            "input": {
                "type": "string",
                "description": f"Input for {cmd.name}",
            },
        },
    }


def tool_record_to_anthropic_schema(record: ToolRecord) -> dict:
    """Convert a single ToolRecord into an Anthropic tool schema dict.

    Returns: {"name": ..., "description": ..., "input_schema": {...}}
    """
    parts: list[str] = []
    if record.commands:
        parts.append(f"Commands: {', '.join(sorted(record.commands))}")
    if record.input_formats:
        parts.append(f"Input: {', '.join(sorted(record.input_formats))}")
    if record.output_formats:
        parts.append(f"Output: {', '.join(sorted(record.output_formats))}")

    description = "; ".join(parts) if parts else record.tool_name

    if record.capability_flags & CapabilityFlags.AUTH_REQUIRED:
        description += " [APPROVAL REQUIRED]"

    return {
        "name": record.tool_name,
        "description": description,
        "input_schema": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "string",
                    "description": f"Input for {record.tool_name}",
                },
            },
        },
    }


def corpus_to_anthropic_schemas(
    entries: Sequence[CorpusEntry],
) -> list[dict]:
    """Convert the full MT-3 corpus into Anthropic tool schemas.

    Generated once, then subsetted by the benchmark.  Schema text is
    identical for any given tool regardless of which arm uses it.
    """
    schemas: list[dict] = []
    for entry in entries:
        d = entry.descriptor
        description = d.description or d.name
        if d.capability_flags & CapabilityFlags.AUTH_REQUIRED:
            description += " [APPROVAL REQUIRED]"

        schemas.append(
            {
                "name": d.name,
                "description": description,
                "input_schema": _infer_input_schema(d),
            }
        )
    return schemas
